CREATE TABLE IF NOT EXISTS `#__hospital_documentos` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `asset_id` int unsigned NOT NULL DEFAULT 0,
  `catid` int unsigned NOT NULL DEFAULT 0,
  `codigo` varchar(40) NOT NULL DEFAULT '',
  `titulo` varchar(255) NOT NULL DEFAULT '',
  `alias` varchar(255) NOT NULL DEFAULT '',
  `descricao` mediumtext,
  `setor` varchar(150) NOT NULL DEFAULT '',
  `versao` varchar(20) NOT NULL DEFAULT '1.0',
  `data_publicacao` date,
  `data_revisao` date,
  `arquivo` varchar(400) NOT NULL DEFAULT '',
  `autor` varchar(150) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'vigente',
  `publico_alvo` varchar(255) NOT NULL DEFAULT '',
  `state` tinyint NOT NULL DEFAULT 1,
  `ordering` int NOT NULL DEFAULT 0,
  `hits` int unsigned NOT NULL DEFAULT 0,
  `created` datetime NOT NULL,
  `created_by` int unsigned NOT NULL DEFAULT 0,
  `modified` datetime NOT NULL,
  `modified_by` int unsigned NOT NULL DEFAULT 0,
  `checked_out` int unsigned,
  `checked_out_time` datetime,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_codigo` (`codigo`),
  KEY `idx_catid` (`catid`),
  KEY `idx_state_status` (`state`, `status`),
  KEY `idx_publicacao` (`data_publicacao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
